export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIES_SEARCH = 'MOVIES_SEARCH';
export const MOVIES_PAGE = 'MOVIES_PAGE';
export const MOVIES_DATA = 'MOVIES_DATA';
export const MOVIES_TOTAL = 'MOVIES_TOTAL';

export const MOVIES_DETAIL_LOADING = 'MOVIES_DETAIL_LOADING';
export const MOVIES_DETAIL_DATA = 'MOVIES_DETAIL_DATA';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';